export default {
  text: {
    color: 'secondary',
    size: 7,
    translateNumbers: true,
  },
  indicator: {
    size: 8,
    color: 'secondary',
  },
  icon: {
    size: 8,
    color: 'black',
    type: 'ion',
  },
  button: {
    size: 6,
    color: 'white',
    bold: false,
    backgroundColor: 'secondary',
    borderWidth: 0,
    borderColor: '#FFFFFF',
    elevation: 0,
    ph: 4,
    pv: 5,
    disabledColor: '#f3f4f5',
    disabledBackgroundColor: 'disabled',
  },
  image: {
    resizeMode: 'cover',
    progressColor: 'primaryLight',
    errorColor: 'black',
    errorBackgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  inputError: {
    color: 'error',
    sizeScale: 0.7,
  },
  input: {
    size: 7,
    activeColor: 'black',
    inactiveColor: 'black',
    backgroundColor: 'transparent',
    placeholderColor: 'thirdly',
    center: false,
    bold: false,
    translateNumbers: true,
    pv: 4,
    ph: 4,
    bc: '#DADADA',
    bw: 1,
    borderRadius: 4,
    height: 7.5,
  },
  textArea: {
    size: 7,
    color: 'black',
    backgroundColor: 'white',
    placeholderColor: 'primary',
    height: 20,
    pv: 0.5,
    ph: 4,
    bc: '#DADADA',
    bw: 1,
    borderRadius: 4,
    translateNumbers: false,
    underlineColor: 'transparent',
  },
  picker: {
    size: 7,
    color: 'primary',
    backgroundColor: 'white',
    pv: 4,
    ph: 4,
    bc: '#DADADA',
    bw: 1,
    borderRadius: 4,
    height: 7.5,
  },
  datePicker: {
    size: 7,
    color: '#A6A6A6',
    backgroundColor: '#F8F8F8',
    pv: 4,
    ph: 4,
    bc: '#DADADA',
    bw: 1,
    borderRadius: 4,
    height: 7.5,
  },
  radioButton: {
    activeColor: 'orange',
    normalColor: '#333333',
    size: 7,
    labelColor: 'black',
  },
  checkBox: {
    activeColor: 'primary',
    normalColor: '#333333',
    size: 7,
    labelColor: 'black',
  },
  list: {
    indicatorColor: 'primary',
    errorLabelColor: 'error',
    noResultsLabelColor: 'black',
    retryButtonBackgroundColor: 'primary',
    retryButtoncolor: 'white',
  },
  tabBar: {
    height: 7,
    backgroundColor: 'white',
    activeTextColor: 'black',
    activeTextSize: 7,
    activeTextBold: true,
    inactiveTextColor: 'primary',
    inactiveTextSize: 7,
    inactiveTextBold: false,
    underlineColor: 'secondary',
    underlineHeight: 3,
  },
  swiper: {
    indicatorColor: 'rgba(255, 255, 255, 0.5)',
    indicatorActiveColor: 'rgba(255, 255, 255, 1)',
  },
  localNotifications: {
    info: {
      backgroundColor: 'secondary',
      closeColor: 'white',
    },
    success: {
      backgroundColor: 'safe',
      closeColor: 'primary',
    },
    error: {
      backgroundColor: 'thirdly',
      closeColor: 'white',
    },
  },
};
